//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MODEL.ViewModels;

namespace MODEL
{    
    public partial class TecnicoElemento
    {
        public int idTecnicoElemento { get; set; }
        public int cantidad { get; set; }
        public string idTecnico { get; set; }
        public int idElemento { get; set; }

        public string elemento { get; set; }
        public virtual Elemento Elemento { get; set; }
        public virtual Tecnico Tecnico { get; set; }

        public static implicit operator TecnicoElemento(TecnicoElementoViewModel tecnicoElementViewModel)
        {
            TecnicoElemento TecnicoElemento = new TecnicoElemento();
            TecnicoElemento.cantidad = tecnicoElementViewModel.cantidad;
            TecnicoElemento.idElemento = tecnicoElementViewModel.idElemento;
            return TecnicoElemento;
        }
    }
}
