//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using MODEL.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    
        public string idTecnico { get; set; }
        public string nombre { get; set; }
        public int salario { get; set; }
        public int IdSucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnicoElemento> TecnicoElementoes { get; set; }

        public static implicit operator Tecnico(TecnicoViewModel tecnicoViewModel)
        {
            Tecnico tecnico = new Tecnico();
            tecnico.idTecnico = tecnicoViewModel.idTecnico;
            tecnico.nombre = tecnicoViewModel.nombre;
            tecnico.salario = tecnicoViewModel.salario;
            tecnico.IdSucursal = tecnicoViewModel.IdSucursal;
            return tecnico;
        }

        public static implicit operator Tecnico(TecnicoElementoViewModel v)
        {
            throw new NotImplementedException();
        }
    }
}
